#!/usr/bin/env python3
"""Static source contract for newly promoted high-level AscTile operators.

This is a conservative AST policy check, not a security sandbox, Python type
checker, or proof of numerical correctness. It never imports candidate code.
Operators must be self-contained: arbitrary imported helpers cannot be audited
here. The sole runtime exception is the host-side ensure_npu_platform helper;
when present beside an operator, its entire source is audited as platform setup.
Only authored Python is checked; registers generated by vf_fusion are legal.
Historical source/artifacts are checked only when selected for a new promotion.
"""

from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path


# Public compute/type exports from asctile, deliberately excluding inline,
# inline_vf and runtime/compiler/profiling access. No runtime import is needed.
ASCTILE_PUBLIC = set("""
    ConstExpr DataType GlobalAddress GlobalTensor LocalTensor RoundMode
    TensorLocation bfloat16 bool_ float16 float32 float64 float_ int8 int16
    int32 int64 int_ global_tensor range static_range ceildiv jit
    atomic_add atomic_max atomic_min add bitwise_and bitwise_or bitwise_xor
    div equal greater greater_equal left_shift less less_equal matmul
    matmul_acc maximum minimum mul not_equal pow right_shift sub cast concat
    full full_like zeros zeros_acc zeros_like copy copy_in copy_out gather
    scatter block_idx block_num sub_block_idx sub_block_num broadcast_shapes
    broadcast_tensors broadcast_to expand_dims ravel reshape squeeze transpose
    abs bitwise_not ceil cos cosh erf exp exp2 floor layer_norm log log2 negative
    relu rms_norm rsqrt sin sinh softmax sqrt tan tanh mask where
    reduce_max reduce_min reduce_sum reduce_prod
""".split())
TORCH_ALLOCATIONS = {"empty", "empty_like", "empty_strided", "zeros", "zeros_like",
                     "ones", "ones_like", "full", "full_like", "tensor"}
TORCH_TYPES = set("""
    Tensor Size dtype device layout memory_format strided contiguous_format
    preserve_format channels_last channels_last_3d float16 half bfloat16 float32
    float float64 double int8 uint8 int16 short int32 int int64 long bool
""".split())
TORCH_METADATA = {"numel", "is_tensor", "is_floating_point", "finfo", "iinfo"}
TENSOR_METADATA = {"shape", "dtype", "device", "ndim", "layout", "requires_grad",
                   "is_cuda", "is_cpu", "is_npu", "size", "stride", "numel", "dim",
                   "element_size", "is_contiguous", "is_floating_point"}
TENSOR_VIEWS = {"view", "reshape", "flatten", "ravel", "squeeze", "unsqueeze",
                "narrow", "select", "transpose", "permute", "contiguous", "detach"}
TENSOR_ALLOCATIONS = {"new_empty", "new_empty_strided", "new_zeros", "new_ones",
                      "new_full"}
FORBIDDEN_NAMES = {"inline", "inline_vf", "custom_jit", "RegTensor", "MaskReg",
                   "TQue", "TBuf", "TPipe", "TPosition", "Hardware", "PipeID"}
DYNAMIC_NAMES = {"exec", "eval", "compile", "__import__", "getattr", "setattr",
                 "delattr", "globals", "locals", "vars", "open"}
HOST_IMPORTS = {"math", "typing", "__future__"}
RUNTIME_HELPER = "_pyasc_runtime.ensure_npu_platform"
TENSOR = "<torch-tensor>"


class _SourceCheck(ast.NodeVisitor):
    def __init__(self) -> None:
        self.bindings: dict[str, str] = {}
        self.problems: set[str] = set()
        self.in_kernel = False
        self.has_jit = False
        self.has_asctile_import = False

    def fail(self, node: ast.AST, message: str) -> None:
        self.problems.add(f"line {getattr(node, 'lineno', 1)}: {message}")

    def resolve(self, node: ast.AST | None) -> str:
        if isinstance(node, ast.Name):
            return self.bindings.get(node.id, node.id)
        if isinstance(node, ast.Attribute):
            base = self.resolve(node.value)
            return f"{base}.{node.attr}" if base else ""
        if isinstance(node, ast.Subscript):
            base = self.resolve(node.value)
            return TENSOR if base == TENSOR else ""
        if isinstance(node, ast.Call):
            name = self.resolve(node.func)
            if name in {f"torch.{x}" for x in TORCH_ALLOCATIONS}:
                return TENSOR
            if name.startswith(TENSOR + "."):
                method = name.rsplit(".", 1)[-1]
                if method in TENSOR_VIEWS | TENSOR_ALLOCATIONS:
                    return TENSOR
            # Preserve tensor provenance through common host containers.
            if name in {"list", "tuple", "zip", "enumerate", "iter"}:
                if any(self.resolve(arg) == TENSOR for arg in node.args):
                    return TENSOR
        if isinstance(node, (ast.List, ast.Tuple)):
            if any(self.resolve(item) == TENSOR for item in node.elts):
                return TENSOR
        if isinstance(node, ast.IfExp):
            if TENSOR in {self.resolve(node.body), self.resolve(node.orelse)}:
                return TENSOR
        return ""

    def check_name(self, node: ast.AST, name: str) -> None:
        parts = name.split(".")
        root = parts[0]
        if root in {"asc", "asc2"}:
            self.fail(node, f"low-level {name} is forbidden; use asctile public APIs")
        if any(part in FORBIDDEN_NAMES for part in parts):
            self.fail(node, f"authored low-level/inline helper is forbidden: {name}")
        if root in DYNAMIC_NAMES or root in {"ctypes", "importlib", "builtins"}:
            self.fail(node, f"dynamic execution/import/access is forbidden: {name}")
        if any(part.startswith("__") for part in parts) and root != "__future__":
            self.fail(node, f"dynamic dunder access is forbidden: {name}")
        if root == "asctile" and len(parts) > 1:
            if parts[1] not in ASCTILE_PUBLIC or (
                len(parts) > 2 and parts[1] not in {"RoundMode", "TensorLocation", "DataType"}
            ):
                self.fail(node, f"not an allowed asctile public API: {name}")
        if root == "torch" and len(parts) > 1:
            if parts[1] not in TORCH_ALLOCATIONS | TORCH_TYPES | TORCH_METADATA or (
                len(parts) > 2 and not (parts[1] == "Tensor" and parts[2] in TENSOR_METADATA | TENSOR_VIEWS | TENSOR_ALLOCATIONS)
            ):
                self.fail(node, f"torch numerical/unsupported API is forbidden: {name}")
            elif self.in_kernel:
                self.fail(node, f"torch belongs in host allocation/metadata only: {name}")
        if root == "_pyasc_runtime":
            if name != RUNTIME_HELPER:
                self.fail(node, f"runtime exception permits only {RUNTIME_HELPER}: {name}")
            elif self.in_kernel:
                self.fail(node, "ensure_npu_platform is permitted only on the host")
        if root == TENSOR and len(parts) > 1:
            if parts[1] not in TENSOR_METADATA | TENSOR_VIEWS | TENSOR_ALLOCATIONS:
                self.fail(node, f"torch Tensor numerical/unsupported API is forbidden: {name}")

    def visit_Name(self, node: ast.Name) -> None:
        if isinstance(node.ctx, ast.Load):
            self.check_name(node, self.resolve(node))

    def visit_Attribute(self, node: ast.Attribute) -> None:
        self.check_name(node, self.resolve(node))
        if node.attr == "data_ptr":
            self.fail(node, "Tensor.data_ptr is forbidden; pass tensors to the JIT")
        # Tile.to is legal; host Tensor.to is rejected via provenance above.
        self.generic_visit(node)

    def visit_Import(self, node: ast.Import) -> None:
        for alias in node.names:
            self.check_import(node, alias.name)
            self.bindings[alias.asname or alias.name.split(".")[0]] = (
                alias.name if alias.asname else alias.name.split(".")[0]
            )

    def check_import(self, node: ast.AST, name: str) -> None:
        self.check_name(node, name)
        self.has_asctile_import |= name == "asctile"
        if name not in {"asctile", "torch"} | HOST_IMPORTS:
            self.fail(node, f"imported helper/module is outside the source contract: {name}")

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        module = node.module or ""
        runtime = module == "_pyasc_runtime" and node.level in {0, 1}
        if not runtime:
            if node.level:
                self.fail(node, f"imported helper is outside the source contract: {'.' * node.level}{module}")
            self.check_import(node, module)
        for alias in node.names:
            name = f"{module}.{alias.name}"
            if alias.name == "*":
                self.fail(node, "wildcard imports are outside the source contract")
            self.check_name(node, name)
            self.bindings[alias.asname or alias.name] = name

    def bind(self, target: ast.AST, value: ast.AST | None) -> None:
        if isinstance(target, ast.Name):
            self.bindings[target.id] = self.resolve(value)
        elif isinstance(target, (ast.Tuple, ast.List)):
            if isinstance(value, (ast.Tuple, ast.List)) and len(target.elts) == len(value.elts):
                for item, expr in zip(target.elts, value.elts):
                    self.bind(item, expr)
            else:
                for item in target.elts:
                    self.bind(item, value)

    def visit_Assign(self, node: ast.Assign) -> None:
        self.visit(node.value)
        for target in node.targets:
            self.visit(target)
            self.bind(target, node.value)

    def visit_AnnAssign(self, node: ast.AnnAssign) -> None:
        self.visit_annotation(node.annotation)
        if node.value is not None:
            self.visit(node.value)
        self.visit(node.target)
        self.bind(node.target, node.value)

    def visit_NamedExpr(self, node: ast.NamedExpr) -> None:
        self.visit(node.value)
        self.bind(node.target, node.value)

    def visit_If(self, node: ast.If) -> None:
        self.visit(node.test)
        before = self.bindings.copy()
        for statement in node.body:
            self.visit(statement)
        body = self.bindings
        self.bindings = before.copy()
        for statement in node.orelse:
            self.visit(statement)
        for name in body.keys() | self.bindings.keys():
            left, right = body.get(name, ""), self.bindings.get(name, "")
            self.bindings[name] = TENSOR if TENSOR in {left, right} else left or right

    def visit_For(self, node: ast.For) -> None:
        self.visit(node.iter)
        self.bind_iteration(node.target, node.iter)
        for statement in node.body + node.orelse:
            self.visit(statement)

    def visit_comprehension(self, node: ast.comprehension) -> None:
        self.visit(node.iter)
        self.bind_iteration(node.target, node.iter)
        for condition in node.ifs:
            self.visit(condition)

    def bind_iteration(self, target: ast.AST, value: ast.AST) -> None:
        if isinstance(value, ast.Call) and isinstance(target, (ast.Tuple, ast.List)):
            name = self.resolve(value.func)
            if name == "enumerate" and len(target.elts) == 2 and value.args:
                self.bind(target.elts[0], None)
                self.bind(target.elts[1], value.args[0])
                return
            if name == "zip" and len(target.elts) == len(value.args):
                for item, iterable in zip(target.elts, value.args):
                    self.bind(item, iterable)
                return
        self.bind(target, value)

    def visit_ListComp(self, node: ast.ListComp) -> None:
        old = self.bindings.copy()
        for generator in node.generators:
            self.visit(generator)
        self.visit(node.elt)
        self.bindings = old

    visit_GeneratorExp = visit_ListComp
    visit_SetComp = visit_ListComp

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        jit = any(self.resolve(d.func if isinstance(d, ast.Call) else d) == "asctile.jit"
                  for d in node.decorator_list)
        self.has_jit |= jit
        for decorator in node.decorator_list:
            self.visit(decorator)
        for default in node.args.defaults + [d for d in node.args.kw_defaults if d]:
            self.visit(default)
        for arg in node.args.posonlyargs + node.args.args + node.args.kwonlyargs:
            if arg.annotation:
                self.visit_annotation(arg.annotation)
        if node.returns:
            self.visit_annotation(node.returns)
        old, old_kernel = self.bindings.copy(), self.in_kernel
        self.in_kernel = jit or old_kernel
        args = node.args.posonlyargs + node.args.args
        defaults = [None] * (len(args) - len(node.args.defaults)) + node.args.defaults
        for arg, default in zip(args + node.args.kwonlyargs, defaults + node.args.kw_defaults):
            annotation = self.resolve(arg.annotation)
            if isinstance(arg.annotation, ast.Constant) and isinstance(arg.annotation.value, str):
                annotation = arg.annotation.value
            scalar = annotation in {"int", "float", "bool", "str"} or isinstance(default, ast.Constant) and default.value is not None
            # Unannotated host inputs are conservatively tensor-like. Scalar
            # helpers can use scalar annotations; metadata results are scalars.
            self.bindings[arg.arg] = "" if self.in_kernel or scalar else TENSOR
        for arg in (node.args.vararg, node.args.kwarg):
            if arg:
                self.bindings[arg.arg] = "" if self.in_kernel else TENSOR
        for statement in node.body:
            self.visit(statement)
        self.bindings, self.in_kernel = old, old_kernel

    visit_AsyncFunctionDef = visit_FunctionDef

    def visit_Lambda(self, node: ast.Lambda) -> None:
        for default in node.args.defaults + [d for d in node.args.kw_defaults if d]:
            self.visit(default)
        old = self.bindings.copy()
        for arg in node.args.posonlyargs + node.args.args + node.args.kwonlyargs:
            self.bindings[arg.arg] = "" if self.in_kernel else TENSOR
        self.visit(node.body)
        self.bindings = old

    def visit_annotation(self, node: ast.AST) -> None:
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            try:
                annotation = ast.parse(node.value, mode="eval")
            except SyntaxError:
                self.fail(node, "cannot parse forward type annotation")
                return
            ast.increment_lineno(annotation, node.lineno - 1)
            self.visit(annotation)
        else:
            self.visit(node)

    def check_tensor_math(self, node: ast.AST, values: list[ast.AST]) -> None:
        if not self.in_kernel and any(self.resolve(value) == TENSOR for value in values):
            self.fail(node, "torch Tensor numerical work must be expressed in an asctile kernel")
        self.generic_visit(node)

    def visit_BinOp(self, node: ast.BinOp) -> None:
        self.check_tensor_math(node, [node.left, node.right])

    def visit_AugAssign(self, node: ast.AugAssign) -> None:
        self.check_tensor_math(node, [node.target, node.value])

    def visit_UnaryOp(self, node: ast.UnaryOp) -> None:
        self.check_tensor_math(node, [node.operand])

    def visit_Compare(self, node: ast.Compare) -> None:
        if all(isinstance(op, (ast.Is, ast.IsNot)) for op in node.ops):
            self.generic_visit(node)
        else:
            self.check_tensor_math(node, [node.left, *node.comparators])

    def visit_Call(self, node: ast.Call) -> None:
        name = self.resolve(node.func)
        if name == RUNTIME_HELPER and (node.args or node.keywords):
            self.fail(node, "runtime exception permits only ensure_npu_platform() with no arguments")
        if name in {"abs", "sum", "min", "max", "pow", "float", "int", "bool"} or name.startswith("math."):
            if any(self.resolve(arg) == TENSOR for arg in node.args):
                self.fail(node, f"host numerical work on a torch Tensor is forbidden: {name}")
        self.generic_visit(node)


class _RuntimeCheck(_SourceCheck):
    """Narrow AST grammar for the optional platform-setup helper, not kernels.

    Audit the whole module, including unused definitions and import-time code.
    Canonical asc.runtime.config setup and public asctile setup are equivalent
    here; neither exception admits compiler/JIT objects or mutation of objects.
    """

    IMPORTS = {"os", "threading", "asctile", "asc.runtime.config", "__future__"}
    CONFIG = {"asc.runtime.config", "asctile"}
    LOCK_CALLS = {"threading.Lock", "threading.RLock"}
    ENV_CALLS = {"os.getenv", "os.environ.get"}
    CONFIG_CALLS = {f"{module}.{name}" for module in ("asc.runtime.config", "asctile")
                    for name in ("Platform", "set_platform")}
    ALLOWED_NODES = (
        ast.Module, ast.Import, ast.ImportFrom, ast.alias, ast.FunctionDef,
        ast.Expr, ast.Assign, ast.AnnAssign, ast.Name, ast.Load, ast.Store,
        ast.Constant, ast.Attribute, ast.Call, ast.keyword, ast.Global,
        ast.If, ast.With, ast.withitem, ast.Return, ast.Pass, ast.Try,
        ast.ExceptHandler, ast.Raise, ast.Compare, ast.cmpop, ast.BoolOp,
        ast.boolop, ast.UnaryOp, ast.Not, ast.JoinedStr, ast.FormattedValue,
        ast.ListComp, ast.comprehension, ast.List, ast.Tuple, ast.Subscript,
    )

    def __init__(self) -> None:
        super().__init__()
        self.in_setup = False
        self.setup_count = 0

    def visit(self, node: ast.AST):
        if not isinstance(node, self.ALLOWED_NODES):
            self.fail(node, f"runtime helper permits only host platform setup: {type(node).__name__}")
        return super().visit(node)

    def check_name(self, node: ast.AST, name: str) -> None:
        parts = name.split(".")
        if any(part in FORBIDDEN_NAMES | DYNAMIC_NAMES or part.startswith("__")
               for part in parts) and name != "__future__.annotations":
            self.fail(node, f"forbidden runtime helper symbol: {name}")
        allowed = self.IMPORTS | self.CONFIG_CALLS | self.LOCK_CALLS | self.ENV_CALLS | {
            "os.environ", "asc.runtime", "__future__.annotations", "<platform>.value",
        }
        for module in self.CONFIG:
            allowed.update({f"{module}.Backend", f"{module}.Backend.NPU"})
            # Platform enum members are host configuration values.
            if name.startswith(f"{module}.Platform."):
                member = name.removeprefix(f"{module}.Platform.")
                if member.isidentifier() and not member.startswith("_"):
                    allowed.add(name)
        if "." in name and name not in allowed:
            self.fail(node, f"runtime helper API is outside host platform setup: {name}")

    def check_import(self, node: ast.AST, name: str) -> None:
        if name not in self.IMPORTS:
            self.fail(node, f"runtime helper import is outside host platform setup: {name}")

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        if node.level:
            self.fail(node, "runtime helper must not import other local helpers")
        module = node.module or ""
        self.check_import(node, module)
        for alias in node.names:
            name = f"{module}.{alias.name}"
            self.check_name(node, name)
            self.bindings[alias.asname or alias.name] = name

    def resolve(self, node: ast.AST | None) -> str:
        if isinstance(node, ast.Call):
            name = self.resolve(node.func)
            if name in self.LOCK_CALLS:
                return "<lock>"
            if name in {f"{module}.Platform" for module in self.CONFIG}:
                return "<platform>"
        return super().resolve(node)

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        self.setup_count += 1
        if node.name != "ensure_npu_platform" or self.in_setup:
            self.fail(node, f"runtime helper may define only ensure_npu_platform: {node.name}")
        if (node.decorator_list or node.args.posonlyargs or node.args.args
                or node.args.kwonlyargs or node.args.vararg or node.args.kwarg):
            self.fail(node, "ensure_npu_platform must be an undecorated zero-argument host function")
        old, old_setup = self.bindings.copy(), self.in_setup
        # Defaults, annotations and decorators are also authored source and may
        # execute at import time, even on a definition that is never called.
        for expression in (node.decorator_list + node.args.defaults
                           + [d for d in node.args.kw_defaults if d]):
            self.visit(expression)
        for arg in node.args.posonlyargs + node.args.args + node.args.kwonlyargs:
            if arg.annotation:
                self.visit_annotation(arg.annotation)
        if node.returns:
            self.visit_annotation(node.returns)
        self.in_setup = True
        for statement in node.body:
            self.visit(statement)
        self.bindings, self.in_setup = old, old_setup

    def visit_Attribute(self, node: ast.Attribute) -> None:
        if isinstance(node.ctx, ast.Store):
            self.fail(node, "runtime helper object mutation/monkeypatch is forbidden")
        super().visit_Attribute(node)

    def visit_Subscript(self, node: ast.Subscript) -> None:
        if isinstance(node.ctx, ast.Store):
            self.fail(node, "runtime helper object mutation/monkeypatch is forbidden")
        if (self.resolve(node.value) != "os.environ"
                or not isinstance(node.slice, ast.Constant)
                or node.slice.value != "CANN_BENCH_PYASC_PLATFORM"):
            self.fail(node, "runtime helper subscripts are limited to the platform environment override")
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        name = self.resolve(node.func)
        allowed = self.LOCK_CALLS | self.ENV_CALLS | self.CONFIG_CALLS | {"RuntimeError", "ValueError"}
        if name not in allowed:
            self.fail(node, f"runtime helper call is outside host platform setup: {name or '<indirect>'}")
        if not self.in_setup and name not in self.LOCK_CALLS:
            self.fail(node, "runtime helper import-time calls are limited to lock creation")
        if name in self.ENV_CALLS and (
            not node.args or not isinstance(node.args[0], ast.Constant)
            or node.args[0].value != "CANN_BENCH_PYASC_PLATFORM"
        ):
            self.fail(node, "runtime helper may read only the platform environment override")
        self.generic_visit(node)

    def visit_With(self, node: ast.With) -> None:
        for item in node.items:
            if self.resolve(item.context_expr) != "<lock>":
                self.fail(item.context_expr, "runtime helper context managers must be threading locks")
        self.generic_visit(node)

    def bind_iteration(self, target: ast.AST, value: ast.AST) -> None:
        if self.resolve(value) in {f"{module}.Platform" for module in self.CONFIG} and isinstance(target, ast.Name):
            self.bindings[target.id] = "<platform>"
        else:
            self.fail(value, "runtime helper iteration is limited to platform enum metadata")

    def visit_Return(self, node: ast.Return) -> None:
        if node.value is not None and not (isinstance(node.value, ast.Constant) and node.value.value is None):
            self.fail(node, "ensure_npu_platform must not return numerical work or helpers")
        self.generic_visit(node)


def check_runtime_helper(path: Path | str) -> list[str]:
    """Audit an existing helper without importing it; absent draft helpers pass."""
    path = Path(path)
    if not path.exists() and not path.is_symlink():
        return []
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except (OSError, UnicodeError, SyntaxError) as exc:
        return [f"{path}: cannot parse runtime helper: {exc}"]
    check = _RuntimeCheck()
    check.visit(tree)
    if check.setup_count != 1:
        check.problems.add("runtime helper must define exactly one ensure_npu_platform function")
    return [f"{path}: {problem}" for problem in sorted(check.problems)]


def check_high_level_source(path: Path | str) -> list[str]:
    """Return actionable source-contract violations without executing the file."""
    try:
        tree = ast.parse(Path(path).read_text(encoding="utf-8"), filename=str(path))
    except (OSError, UnicodeError, SyntaxError) as exc:
        return [f"cannot parse source: {exc}"]
    check = _SourceCheck()
    check.visit(tree)
    if not check.has_jit or not check.has_asctile_import:
        check.problems.add("no @asctile.jit kernel found (import/assignment aliases are supported)")
    return sorted(check.problems) + check_runtime_helper(Path(path).parent / "_pyasc_runtime.py")


def package_sources(package: Path, promotions: Path | None = None) -> list[Path]:
    """Select operator files; each source check also audits the package helper."""
    if promotions is not None:
        operators = json.loads(promotions.read_text(encoding="utf-8"))
        if not isinstance(operators, list) or not operators or not all(
            isinstance(op, str) and op.isidentifier() and not op.startswith("_")
            for op in operators
        ):
            raise ValueError("promotions must be a nonempty JSON list of operator names")
        paths = [package / f"{op}.py" for op in operators]
    else:
        paths = sorted(path for path in package.glob("*.py") if not path.name.startswith("_"))
    if not paths:
        raise ValueError(f"no authored operator sources in {package}")
    return paths


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", nargs="*", type=Path)
    parser.add_argument("--package", type=Path)
    parser.add_argument("--promotions", type=Path, help="JSON list of newly promoted operator names")
    args = parser.parse_args()
    paths = args.paths
    if args.package:
        try:
            paths += package_sources(args.package, args.promotions)
        except (ValueError, OSError) as exc:
            parser.error(str(exc))
    elif args.promotions:
        parser.error("--promotions requires --package")
    if not paths:
        parser.error("select at least one authored operator source")
    failures = {str(path): problems for path in paths if (problems := check_high_level_source(path))}
    print(json.dumps({"status": "failed" if failures else "passed", "failures": failures}, indent=2))
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
